name: Build LaTeX document
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Prepare for Pages
        run: |
          mkdir public
          mv main.pdf public/
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
